//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quitr2.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviation
    {
        public int Id { get; set; }
        public int userprefid { get; set; }
        public Nullable<System.DateTime> deviation_start { get; set; }
        public Nullable<System.DateTime> deviation_end { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual userpref userpref { get; set; }
    }
}
