//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quitr2.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ginoEntities1 : DbContext
    {
        public ginoEntities1()
            : base("name=ginoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<addictiontype> addictiontypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<deviation> deviations { get; set; }
        public virtual DbSet<mood> moods { get; set; }
        public virtual DbSet<productcontent> productcontents { get; set; }
        public virtual DbSet<productcontenttype> productcontenttypes { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<substitute> substitutes { get; set; }
        public virtual DbSet<substitutestat> substitutestats { get; set; }
        public virtual DbSet<userpref> userprefs { get; set; }
        public virtual DbSet<nicotine_per_day> nicotine_per_day { get; set; }
        public virtual DbSet<substitute_nicotine_per_day> substitute_nicotine_per_day { get; set; }
        public virtual DbSet<substitute_nicotine_today> substitute_nicotine_today { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<achivement> achivements { get; set; }
        public virtual DbSet<userachivement> userachivements { get; set; }
    }
}
