//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quitr2.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class substitutestat
    {
        public int Id { get; set; }
        public int substituteId { get; set; }
        public System.DateTime TS { get; set; }
    
        public virtual substitute substitute { get; set; }
    }
}
