//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quitr2.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class userachivement
    {
        public int Id { get; set; }
        public int userprefid { get; set; }
        public int achivementid { get; set; }
        public System.DateTime TS { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> achivementtype { get; set; }
    
        public virtual achivement achivement { get; set; }
        public virtual userpref userpref { get; set; }
    }
}
