//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quitr2.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class userpref
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userpref()
        {
            this.deviations = new HashSet<deviation>();
            this.moods = new HashSet<mood>();
            this.substitutes = new HashSet<substitute>();
            this.userachivements = new HashSet<userachivement>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> stopDate { get; set; }
        public int addictiontype { get; set; }
        public string userId { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> units { get; set; }
        public Nullable<int> addictionproducttype { get; set; }
        public Nullable<System.DateTime> deleteDate { get; set; }
        public Nullable<bool> sharing { get; set; }
        public Nullable<bool> substituteUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deviation> deviations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mood> moods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<substitute> substitutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userachivement> userachivements { get; set; }
    }
}
